package models

import "time"

// FAQ represents a client-specific Frequently Asked Question.
// It can be generated by AI from website scrapes or manually created.
type FAQ struct {
	ID         string    `json:"id"`
	ClientID   string    `json:"client_id"`
	Question   string    `json:"question"`
	Answer     string    `json:"answer"`
	IsApproved bool      `json:"is_approved"`
	CreatedAt  time.Time `json:"created_at"`
}

// CreateFAQRequest is the payload for adding/updating an FAQ
type CreateFAQRequest struct {
	Question   string `json:"question" validate:"required"`
	Answer     string `json:"answer" validate:"required"`
	IsApproved bool   `json:"is_approved"`
}
