package services

import (
	"github.com/codexylab/alvex-backend/pkg/crypto"
	"github.com/codexylab/alvex-backend/pkg/models"
)

// platformKeys holds the platform-level fallback API keys for each provider.
type platformKeys struct {
	EncryptionKey          string
	PreviousEncryptionKeys []string
	Gemini                 string
	OpenAI                 string
	Groq                   string
	FallbackGemini         string
}

// resolveProviderAPIKey selects a write-only provider credential. Machine API
// keys are stored separately and can never be used as AI provider secrets.
func resolveProviderAPIKey(c *models.Client, keys platformKeys) string {
	switch c.Provider {
	case "Gemini":
		if c.GeminiAPIKey != "" {
			return usableProviderKey(c.GeminiAPIKey, keys.EncryptionKey, keys.PreviousEncryptionKeys, keys.Gemini)
		}
		return keys.Gemini

	case "Groq":
		if c.GroqAPIKey != "" {
			return usableProviderKey(c.GroqAPIKey, keys.EncryptionKey, keys.PreviousEncryptionKeys, keys.Groq)
		}
		return keys.Groq

	default: // OpenAI
		if c.OpenAIAPIKey != "" {
			return usableProviderKey(c.OpenAIAPIKey, keys.EncryptionKey, keys.PreviousEncryptionKeys, keys.OpenAI)
		}
		return keys.OpenAI
	}
}

func usableProviderKey(storedKey, encryptionKey string, previousKeys []string, platformKey string) string {
	decrypted := decryptIfNeeded(storedKey, encryptionKey, previousKeys)
	if decrypted == "" || isLegacyAlvexKey(decrypted) {
		return platformKey
	}
	return decrypted
}

// decryptIfNeeded decrypts the key if an encryption key is set and the value is non-empty.
func decryptIfNeeded(key, encKey string, previousKeys []string) string {
	if encKey != "" && key != "" {
		decrypted, _, err := crypto.DecryptAPIKeyWithKeyring(encKey, previousKeys, key)
		if err != nil {
			return ""
		}
		return decrypted
	}
	return key
}

// isLegacyAlvexKey identifies credentials generated by the retired
// clients.api_key flow. They are never accepted as provider or machine keys.
func isLegacyAlvexKey(key string) bool {
	return len(key) >= 5 && key[:5] == "ALVX-"
}
